/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "J2735-AddGrpB.asn"
 * 	`asn1c -gen-PER -fcompound-names -pdu=MessageFrame -D /home/stier/catkin_ws/src/its_bridge/generated/`
 */

#ifndef	_BAngle_H_
#define	_BAngle_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BAngle */
typedef long	 BAngle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BAngle;
asn_struct_free_f BAngle_free;
asn_struct_print_f BAngle_print;
asn_constr_check_f BAngle_constraint;
ber_type_decoder_f BAngle_decode_ber;
der_type_encoder_f BAngle_encode_der;
xer_type_decoder_f BAngle_decode_xer;
xer_type_encoder_f BAngle_encode_xer;
oer_type_decoder_f BAngle_decode_oer;
oer_type_encoder_f BAngle_encode_oer;
per_type_decoder_f BAngle_decode_uper;
per_type_encoder_f BAngle_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BAngle_H_ */
#include <asn_internal.h>
