/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "J2735-AddGrpB.asn"
 * 	`asn1c -gen-PER -fcompound-names -pdu=MessageFrame -D /home/stier/catkin_ws/src/its_bridge/generated/`
 */

#ifndef	_BMsgCount_H_
#define	_BMsgCount_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BMsgCount */
typedef long	 BMsgCount_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BMsgCount;
asn_struct_free_f BMsgCount_free;
asn_struct_print_f BMsgCount_print;
asn_constr_check_f BMsgCount_constraint;
ber_type_decoder_f BMsgCount_decode_ber;
der_type_encoder_f BMsgCount_encode_der;
xer_type_decoder_f BMsgCount_decode_xer;
xer_type_encoder_f BMsgCount_encode_xer;
oer_type_decoder_f BMsgCount_decode_oer;
oer_type_encoder_f BMsgCount_encode_oer;
per_type_decoder_f BMsgCount_decode_uper;
per_type_encoder_f BMsgCount_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BMsgCount_H_ */
#include <asn_internal.h>
