<package format="2">
  <name>control_pose_bridge</name>
  <version>0.0.1</version>
  <description>Pose arbitration &amp; DR backup for PP</description>
  <maintainer email="dhfz1794@naver.com">gksma</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>tf2</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_depend>tf2_geometry_msgs</build_depend>
  <build_depend>ublox_msgs</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>robot_localization</exec_depend>
  <exec_depend>ublox_msgs</exec_depend>
  <exec_depend>erp42_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>roscpp</exec_depend>

  
  <build_export_depend>ublox_msgs</build_export_depend>
  <build_export_depend>roscpp</build_export_depend>

  
</package>
